config/routes.rb
Rails.application.routes.draw do
  get 'all_users' =>'admin#all_users'

  get 'edit_user' =>'admin#edit_user'
  post 'edit_user' => 'admin#edit_user'

  get 'show_user' =>'admin#show_user'

  get 'delete_user' =>'admin#delete_user'

  post 'add_to_cart' => 'cart#add_to_cart'

  get 'view_order' => 'cart#view_order'

  get 'checkout' => 'cart#checkout'

  post 'delete_line_item' => 'cart#delete_line_item'
 	get 'delete_line_item' => 'cart#delete_line_item'

  post 'order_complete' => 'cart#order_complete'

 # post 'delete_user' => 'admin#delete_user'
 # get 'delete_user' => 'admin#delete_user'


	get 'edit_line_item' => 'cart#edit_line_item'

  post 'edit_line_item' => 'cart#edit_line_item'


  root 'storefront#all_items'
  get 'categorical' => 'storefront#items_by_category'
  get 'branding' => 'storefront#items_by_brand'
  
  devise_for :users
  resources :products

  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/cart_controller.rb
class CartController < ApplicationController

	before_action :authenticate_user!, except: [:add_to_cart, :view_order]
  

  def add_to_cart
  	#lets add a message that will not allow our user to add '0' quantity

  	if params[:quantity].to_i == 0
      flash[:notice] = "Please enter a valid quantity to add to cart!"
      redirect_back(fallback_location: root_path) 

      #if user provides valid information we next check to see if the item has already been
      #added to prevent duplicates
  	else

#call current_order      
  	 	 line_item = LineItem.where(product_id: params[:product_id].to_i).first
  	 	 	#if line_item is not found, we create it.
  	 	 	if line_item.blank?
  	 	 		line_item = LineItem.create(product_id: params[:product_id], quantity: params[:quantity])
		  		line_item.update(line_item_total: (line_item.quantity * line_item.product.price))

  	 	 	else
  	 	 	#if found, we update it with the additional quantity
  	 	 	 	new_quantity = line_item.quantity + params[:quantity].to_i
					line_item.update(quantity: new_quantity)
					line_item.update(line_item_total: (line_item.quantity * line_item.product.price))		 

				end	
  		redirect_back(fallback_location: root_path)
  	end
	end



  def view_order
  	@line_items = LineItem.all
    @cart_total = 0

    @line_items.each do |item|
      @cart_total += item.line_item_total
     end 
  end

  def checkout
  	line_items = LineItem.all
  	@order = Order.create(user_id: current_user.id,  subtotal: 0)
  	line_items.each do |line_item|
	  	line_item.product.update(quantity: (line_item.product.quantity - line_item.quantity))
	  	@order.order_items[line_item.product_id] = line_item.quantity
	  	@order.subtotal += line_item.line_item_total
  	end
  	
  	@order.save


	@order.update(sales_tax: (@order.subtotal * 0.08))
	@order.update(grand_total: (@order.sales_tax + @order.subtotal))  
	
	line_items.destroy_all		

  end

  def edit_line_item
  
    line_item = LineItem.where(product_id: params[:product_id].to_i).first
    line_item.update(quantity: params[:quantity].to_i)
    line_item.update(line_item_total: line_item.quantity * line_item.product.price)

    redirect_back(fallback_location: view_order) 

  end 



  def delete_line_item
    
    line_item = LineItem.where(product_id: params[:product_id].to_i).first
    line_item.destroy
    redirect_back(fallback_location: view_order) 

  end  


  def order_complete

    @order = Order.find(params[:order_id])
    @amount = (@order.grand_total.to_f.round(2) * 100).to_i

    customer = Stripe::Customer.create(
      :email => current_user.email,
      :card => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer => customer.id,
      :amount => @amount,
      :description => 'Classic Creations Customer',
      :currency => 'usd'
    )

    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to cart_path

  end 





end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/add_to_cart.html.erb
<h1>Cart#add_to_cart</h1>
<p>Find me in app/views/cart/add_to_cart.html.erb</p>

app/views/cart/checkout.html.erb
<h3>Here is your order summary</h3>

<% @order.order_items.each do |k,v| %>
<div class="well">
  <ul>
    <li><strong>Item:</strong> <%= Product.find(k).name %>,  <strong>Quantity:</strong> <%= v %></li>
  </ul>
</div>
<% end %>

<p>
  <strong>Subtotal: </strong><%= number_to_currency @order.subtotal %> 
</p>

<p>
  <strong>Sales Tax: </strong><%= number_to_currency @order.sales_tax %> 
</p>


<p>
  <strong>Order Total:</strong> <%= number_to_currency @order.grand_total %>
</p>



<div>
  <%= form_tag order_complete_path do %>
    <article>
      <label class="amount">
        <span><%= number_to_currency @order.grand_total %></span>
      </label>
    </article>
    <div>
      <%= hidden_field_tag :order_id, @order.id %>
    </div>

    <script src="http://checkout.stripe.com/checkout.js"
    class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="Order #<%= @order.id %>"
    data-amount="<%= (@order.grand_total.to_f.round(2) * 100) %>"></script>
  <% end %>
</div>

app/views/cart/order_complete.html.erb
<h2>Thank you for shopping with us, <%= @order.user.email %>!</h2>

<p>Your order# <%= @order.id %> will be shipping to you soon.</p>


<p><%= link_to 'Back to Shopping', root_path, class: 'btn btn-success' %></p>

app/views/cart/view_order.html.erb
<h1>Your Cart</h1>

<p>Here are the items you've selected so far:</p>


<div>
	<% if @line_items.blank? %>
		<h2> Your cart is empty!  Go grab some deals!</h2>
		<p><%= link_to "Return to Shopping", root_path, class: 'btn btn-success' %></p>

	<% else %>	
		 <% @line_items.each do |line_item| %>

  <div class="media" >
  	<div class="media-left">
	    <a href="#">
	      <%= image_tag line_item.product.image, class: 'thumb' %>
	    </a>
	  </div>

    <div class="media-body">
	    <h4 class="media-heading"><%= line_item.product.name %></h4>
	    <ul class="list-group">
		    <li class="list-group-item">Price:<%= number_to_currency line_item.product.price %></li>
		    <li class="list-group-item">Qty: <%= line_item.quantity %></li>
		    <li class="list-group-item"><strong>Subtotal: <%= number_to_currency line_item.line_item_total %></strong></li>
	      <li class="list-group-item">

	       <%= form_tag edit_line_item_path do %>
	        <%= hidden_field_tag :order_id, line_item.order_id %>
	        <%= hidden_field_tag :product_id, line_item.product_id %>
	        <%= number_field_tag :quantity, nil, min: 0, max: line_item.product.quantity, class: "form-control" %>
	        <%= submit_tag "Edit Quantity", class: "btn btn-primary" %>
	       <% end %> 
	        <%= link_to "Delete From Cart", delete_line_item_path(product_id: line_item.product_id, order_id: line_item.order_id), class: "btn btn-danger" %>
	      </li>
	      
		  </ul>  
  </div>
</div>

<% end %>



 <h4> Cart Total: <strong><%= number_to_currency @cart_total %></strong></h4>

	<p><%= link_to "Proceed to Checkout?", checkout_path, class: 'btn btn-success'%></p>
<% end %>	


</div>