config/routes.rb
Rails.application.routes.draw do
  get 'all_users' =>'admin#all_users'

  get 'edit_user' =>'admin#edit_user'
  post 'edit_user' => 'admin#edit_user'

  get 'show_user' =>'admin#show_user'

  get 'delete_user' =>'admin#delete_user'

  post 'add_to_cart' => 'cart#add_to_cart'

  get 'view_order' => 'cart#view_order'

  get 'checkout' => 'cart#checkout'

  post 'delete_line_item' => 'cart#delete_line_item'
 	get 'delete_line_item' => 'cart#delete_line_item'

  post 'order_complete' => 'cart#order_complete'

 # post 'delete_user' => 'admin#delete_user'
 # get 'delete_user' => 'admin#delete_user'


	get 'edit_line_item' => 'cart#edit_line_item'

  post 'edit_line_item' => 'cart#edit_line_item'


  root 'storefront#all_items'
  get 'categorical' => 'storefront#items_by_category'
  get 'branding' => 'storefront#items_by_brand'
  
  devise_for :users
  resources :products

  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/all_users.html.erb
	<h1>All Our Users</h1>

	<% @users.each do |user| %>
		<div class="row" style="background: beige; margin-bottom: 10px; padding-top: 5px;">
			<h3><strong>User:</strong> <%= link_to user.email, show_user_path(id: user.id) %></h3>
			<p><strong>Role: </strong><%= user.role %></p>

			
			
		</div>
	<% end %>	
 

app/views/admin/delete_user.html.erb
<h1>Admin#delete_user</h1>
<p>Find me in app/views/admin/delete_user.html.erb</p>

app/views/admin/edit_user.html.erb
<h1>Admin#edit_user</h1>
<p>Find me in app/views/admin/edit_user.html.erb</p>

app/views/admin/show_user.html.erb
<h1>User Profile for <%= @user.email %></h1>


<p>User: <%= @user.email %></p>
<p>Role: <%= @user.role %></p>


<% if can? :manage, User %>

	<div class="well" >

	<%= form_tag edit_user_path do %>
			<%= select_tag(:role, options_for_select([ "admin", "employee", "guest" ]), :prompt => "Please select") %>
			  <%= hidden_field_tag :id, @user.id %>
			  <%= submit_tag "Update Role", class: "btn btn-primary" %>
	<% end %>

		<%= link_to "Delete User", delete_user_path(id: @user.id), class: 'btn btn-danger' %>
	</div>


<% end %>