config/routes.rb
Rails.application.routes.draw do
  get 'all_users' =>'admin#all_users'

  get 'edit_user' =>'admin#edit_user'
  post 'edit_user' => 'admin#edit_user'

  get 'show_user' =>'admin#show_user'

  get 'delete_user' =>'admin#delete_user'

  post 'add_to_cart' => 'cart#add_to_cart'

  get 'view_order' => 'cart#view_order'

  get 'checkout' => 'cart#checkout'

  post 'delete_line_item' => 'cart#delete_line_item'
 	get 'delete_line_item' => 'cart#delete_line_item'

  post 'order_complete' => 'cart#order_complete'

 # post 'delete_user' => 'admin#delete_user'
 # get 'delete_user' => 'admin#delete_user'


	get 'edit_line_item' => 'cart#edit_line_item'

  post 'edit_line_item' => 'cart#edit_line_item'


  root 'storefront#all_items'
  get 'categorical' => 'storefront#items_by_category'
  get 'branding' => 'storefront#items_by_brand'
  
  devise_for :users
  resources :products

  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Win17Ecommerce</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<!-- Start of nav bar -->
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">

          	<li><%= link_to " All Products", root_path %></li>
           <ul class="nav navbar-nav navbar-right">
         
         <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% @categories.each do |category| %>
              <li><%= link_to category.name, categorical_path(id: category.id) %></li>
            <% end %>
            <%= link_to " All Categories", root_path %>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Brands <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% @brands.each do |brand| %>
              <li><%= link_to brand, branding_path(brand: brand) %></li>
            <% end %>
            <%= link_to "All Brands", root_path %>
          </ul>
        </li>



      </ul>
         

          <% if user_signed_in? %>


            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Welcome @<%= current_user.email %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>

            
          
  				<% end %>
            <li><%= link_to "View Cart", view_order_path %></li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
              <ul class="dropdown-menu">
                
                <li><%= link_to "Users", all_users_path %></li>
              
                <li><%= link_to "Inventory", products_path %></li>
              </ul>
            </li>
          
              
        
        </ul>
          </ul><ul class="nav navbar-nav navbar-right nav-title"> <li>Classic Creations</li></ul>

          
          
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
<!-- End of Nav bar -->
<div class="container">
      <div class="cart">
        <% if @line_items.length == 0  %>
          <p><%= link_to "View Cart", view_order_path %><%= image_tag "empty_cart.png", class: 'cart-pic'%></p>
        <% else %>
          <p><%= link_to "View Cart", view_order_path %> <%= image_tag "full_cart.png", class: "cart-pic" %></p>
         <% end %> 
      </div>
</div>
    
  	<div class="container">
    	<%= yield %>
  	</div>
  </body>
</html>